bot:
  name:
    ru: "Цифровой Управляющий Мероприятиями"
    en: "Digital Event Manager"

  description:
    ru: "Описание бота на русском"
    en: "Bot description in English"

  commands:
    ru:
      - command: "start"
        description: "Запустить бота"
    en:
      - command: "start"
        description: "Start the bot"