
services:
  bot:
    image: ${IMAGE_REF}
    restart: unless-stopped
    volumes:
    - tgbot_db:/app/bot/database/instance/
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
  loki:
    image: grafana/loki:3.5.1
  grafana:
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.5.5
    ports:
      - "3000:3000"
volumes:
  tgbot_db:
