name: Python CI
on: [ push, pull_request ]
jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
      with:
        src: source/